DROP DATABASE IF EXISTS ALX_BOOK_STORE;
CREATE DATABASE ALX_BOOK_STORE;
USE ALX_BOOK_STORE;

CREATE TABLE AUTHORS (
    AUTHOR_ID INT NOT NULL PRIMARY KEY,
    AUTHOR_NAME VARCHAR(215)
);

CREATE TABLE CUSTOMERS (
    CUSTOMER_ID INT NOT NULL PRIMARY KEY,
    CUSTOMER_NAME VARCHAR(215),
    EMAIL VARCHAR(215),
    ADDRESS TEXT
);

CREATE TABLE BOOKS (
    BOOK_ID INT NOT NULL PRIMARY KEY,
    TITLE VARCHAR(130),
    AUTHOR_ID INT,
    PRICE DOUBLE,
    PUBLICATION_DATE DATE,
    FOREIGN KEY (AUTHOR_ID) REFERENCES AUTHORS(AUTHOR_ID)
);

