INSERT INTO AUTHORS (AUTHOR_ID, AUTHOR_NAME) VALUES (1, 'J. K. ROWLING');
INSERT INTO AUTHORS (AUTHOR_ID, AUTHOR_NAME) VALUES (2, 'GEORGE ORWELL');
INSERT INTO AUTHORS (AUTHOR_ID, AUTHOR_NAME) VALUES (3, 'AGATHA CHRISTIE');

INSERT INTO CUSTOMERS (CUSTOMER_ID, CUSTOMER_NAME, EMAIL, ADDRESS) VALUES (101, 'ALICE SMITH', 'ALICE@EXAMPLE.COM', '123 MAIN ST');
INSERT INTO CUSTOMERS (CUSTOMER_ID, CUSTOMER_NAME, EMAIL, ADDRESS) VALUES (102, 'BOB JOHNSON', 'BOB@EXAMPLE.COM', '456 OAK AVE');

INSERT INTO BOOKS (BOOK_ID, TITLE, AUTHOR_ID, PRICE, PUBLICATION_DATE) VALUES (1001, 'HARRY POTTER AND THE SORCERER''S STONE', 1, 19.99, '1997-06-26');
INSERT INTO BOOKS (BOOK_ID, TITLE, AUTHOR_ID, PRICE, PUBLICATION_DATE) VALUES (1002, '1984', 2, 12.50, '1949-06-08');
INSERT INTO BOOKS (BOOK_ID, TITLE, AUTHOR_ID, PRICE, PUBLICATION_DATE) VALUES (1003, 'MURDER ON THE ORIENT EXPRESS', 3, 15.75, '1934-01-01');

INSERT INTO ORDERS (ORDER_ID, CUSTOMER_ID, ORDER_DATE) VALUES (1, 101, '2025-10-17');
INSERT INTO ORDERS (ORDER_ID, CUSTOMER_ID, ORDER_DATE) VALUES (2, 102, '2025-10-18');

INSERT INTO ORDER_DETAILS (ORDERDETAILID, ORDER_ID, BOOK_ID, QUANTITY) VALUES (5001, 1, 1001, 2);
INSERT INTO ORDER_DETAILS (ORDERDETAILID, ORDER_ID, BOOK_ID, QUANTITY) VALUES (5002, 1, 1003, 1);
INSERT INTO ORDER_DETAILS (ORDERDETAILID, ORDER_ID, BOOK_ID, QUANTITY) VALUES (5003, 2, 1002, 3);